version: 2.1

jobs:
  test:
    docker:
      - image: mcr.microsoft.com/playwright:v1.52.0-jammy  
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Run Playwright Tests
          command: npx playwright test --reporter=junit
      - store_test_results:
          path: test-results
      - run:
          name: Upload to Zephyr Scale
          command: |
            curl -X POST \
              -H "Authorization: Bearer $ZEPHYR_TOKEN" \
              -H "Content-Type: multipart/form-data" \
              -F "file=@test-results/test-results.xml" \
              "https://api.zephyrscale.smartbear.com/v2/automations/executions/junit?projectKey=AT"
      - run:
          name: Link Execution to Jira Issue
          command: |
            ISSUE_KEY=$(git log -1 --pretty=%B | grep -oE '[A-Z]+-[0-9]+')
            echo "Linking execution to Jira issue: $ISSUE_KEY"

            EXECUTION_KEY=$(curl -s -X GET \
              -H "Authorization: Bearer $ZEPHYR_TOKEN" \
              "https://api.zephyrscale.smartbear.com/v2/testexecutions?projectKey=AT&maxResults=1&orderBy=createdDate&sortOrder=DESC" \
              | jq -r '.values[0].key')

            curl -X POST \
              -H "Authorization: Bearer $ZEPHYR_TOKEN" \
              -H "Content-Type: application/json" \
              -d "{\"issueKeys\": [\"$ISSUE_KEY\"]}" \
              "https://api.zephyrscale.smartbear.com/v2/testexecutions/$EXECUTION_KEY/issues"

workflows:
  test:
    jobs:
      - test
